# nothing here
# Enable the logging subsystem
CONFIG_LOG=y

# Force the initialization of the core kernel-space logging structures


# Minimal logging level for the kernel (Info or Debug)
CONFIG_LOG_MAX_LEVEL=4